# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brandon Purvis
email: ""
description: "A Cool Things Creator | A Python Poet | A Life-Long Learner" 
baseurl: "/brandonPurvis.github.io" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  brandonPurvis

image_url: "https://avatars3.githubusercontent.com/u/6082535?v=4&u=04ce491001112b6598f88e02c29f8d705a45d030&s=400"

# Build settings
markdown: kramdown

# Custom collections
collections:
  projects:
    defaults:
      values:
        layout: post
    output: true

  posts:
    defaults:
      values:
        layout: post
    output: true
